services:
  wallet:
    build: .
    image: crypto-wallet
    container_name: crypto-wallet
    restart: unless-stopped
    networks:
      - infra
    labels:
      - "traefik.enable=true"
      # Basic auth middleware
      - "traefik.http.middlewares.wallet-auth.basicauth.users=primal:$$2y$$05$$c0uQR5.B34.gOIQ9a2Pvi.1zP/dvCcr6Ey.eMGvx07hjzZ8jcyQ7a"
      # Production (HTTPS)
      - "traefik.http.routers.wallet.rule=Host(`wallet.primal.host`)"
      - "traefik.http.routers.wallet.entrypoints=https"
      - "traefik.http.routers.wallet.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wallet.middlewares=wallet-auth"
      # Production HTTP->HTTPS redirect
      - "traefik.http.routers.wallet-redirect.rule=Host(`wallet.primal.host`)"
      - "traefik.http.routers.wallet-redirect.entrypoints=http"
      - "traefik.http.routers.wallet-redirect.middlewares=https-redirect"
      # Local (HTTP)
      - "traefik.http.routers.wallet-local.rule=Host(`wallet.localhost`)"
      - "traefik.http.routers.wallet-local.entrypoints=http"
      - "traefik.http.routers.wallet-local.middlewares=wallet-auth"
      # Service
      - "traefik.http.services.wallet.loadbalancer.server.port=4322"
    dns:
      - 192.168.147.53

networks:
  infra:
    external: true
